### ISSUE TITLE
(autofix-frontend): Fix `marked` console spam

### ISSUE THREAD

**Issue by trillville** [getsentry/seer#1045] opened 2024-08-14 19:00 UTC
Note this component is used by other parts of `sentry`, so we should double-check that the issue is unique to Autofix's usage of it.

```
marked(): highlight and langPrefix parameters are deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-highlight.
```

```
marked.tsx:98 marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options
```

```
marked.tsx:98 marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
```

```
marked.tsx:98 marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
```

**Comment by roaga** [comment] 2024-08-14 22:02
According to @malwilley, this is a Senry-wide problem in the util, not one specific to Autofix's usage of it. So closing this for now. The problem is still unresolved, it just doesn't belong to Autofix.

**Comment by roaga** [comment] 2024-08-14 22:03
According to @malwilley, this is a Senry-wide problem in the util, not one specific to Autofix's usage of it. So closing this for now. The problem is still unresolved, it just doesn't belong to Autofix.

**Closed by roaga** 2024-08-14 22:03 UTC
